name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 * * * *'
    # every hour
  workflow_dispatch:
    inputs:
      upstream_ref:
        description: 'Upstream ref'
        required: true
        default: 'upstream/master'
      merge_into_ref:
        description: 'Ref to merge into'
        required: false
        default: 'master'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ variables.merge_into_ref }}          # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: code1mountain/tdlight-telegram-bot-api
          upstream-branch: ${{ upstream_ref }}
          branch: upstream
