name: Merge Upstream
on: 
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      upstream_owner:
        description: 'Owner of the upstream repository'
        required: true
        default: 'code1mountain'       # set the upstream repo
      upstream_branch:
        description: 'Upstream branch to merge from'
        required: true
        default: 'user-methods'           # set the upstream branch to merge from
      branch:
        description: 'Branch to merge to'
        required: true
        default: 'master'         # set the branch to merge to

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.event.inputs.upstream_owner }}
          base: ${{ github.event.inputs.upstream_branch }}
          head: ${{ github.event.inputs.branch }}
          auto_approve: true
          ignore_fail: false
          personal_token: ${{ secrets.GH_PERSONAL_TOKEN }}  
