name: Merge Upstream
on: 
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      upstream:
        description: 'Upstream repository owner/name. Eg. exions/merge-upstream'
        required: true
        default: 'code1mountain/tdlight-telegram-bot-api'       # set the upstream repo
      upstream_branch:
        description: 'Upstream branch to merge from. Eg. master'
        required: true
        default: 'user-methods'           # set the upstream branch to merge from
      branch:
        description: 'Branch to merge to'
        required: true
        default: 'master'         # set the branch to merge to

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: ${{ github.event.inputs.upstream }}
          upstream-branch: ${{ github.event.inputs.upstream_branch }}
          branch: ${{ github.event.inputs.branch }}
