name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: 'Upstream ref'
        required: true
        default: 'upstream/user-methods'
      merge_into_ref:
        description: 'Ref to merge into'
        required: false
        default: 'master'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.merge_into_ref }}          # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: code1mountain/tdlight-telegram-bot-api
          upstream-branch: ${{ github.event.inputs.upstream_branch }}
          branch: upstream
